import { LeaderboardData } from "./types";

export const leaderboardData: LeaderboardData = {
  "All Time": [
    { id: 1, username: "CSSNinja", score: 9850, challenges: 142, perfectScores: 89, rank: "Grandmaster", avatar: "🥇", trend: { direction: "same", change: 0 } },
    { id: 2, username: "PixelPerfect", score: 9720, challenges: 138, perfectScores: 82, rank: "Grandmaster", avatar: "🥈", trend: { direction: "up", change: 1 } },
    { id: 3, username: "StyleMaster", score: 9680, challenges: 135, perfectScores: 78, rank: "Grandmaster", avatar: "🥉", trend: { direction: "down", change: 1 } },
    { id: 4, username: "CSSWizard", score: 9540, challenges: 130, perfectScores: 75, rank: "Master", avatar: "⭐", trend: { direction: "up", change: 2 } },
    { id: 5, username: "YOU", score: 9480, challenges: 128, perfectScores: 72, rank: "Master", avatar: "👑", trend: { direction: "up", change: 3 } },
    { id: 6, username: "GridGuru", score: 9350, challenges: 125, perfectScores: 68, rank: "Master", avatar: "🎯", trend: { direction: "down", change: 2 } },
    { id: 7, username: "FlexboxHero", score: 9200, challenges: 122, perfectScores: 65, rank: "Diamond", avatar: "💎", trend: { direction: "down", change: 1 } },
    { id: 8, username: "WebArtist", score: 9100, challenges: 120, perfectScores: 62, rank: "Diamond", avatar: "🎨", trend: { direction: "same", change: 0 } },
    { id: 9, username: "CSSPro", score: 8950, challenges: 118, perfectScores: 58, rank: "Diamond", avatar: "🌟", trend: { direction: "down", change: 1 } },
    { id: 10, username: "StyleGenius", score: 8800, challenges: 115, perfectScores: 55, rank: "Diamond", avatar: "✨", trend: { direction: "up", change: 1 } },
  ],
  "This Month": [
    { id: 1, username: "YOU", score: 920, challenges: 15, perfectScores: 10, rank: "Master", avatar: "👑", trend: { direction: "up", change: 4 } },
    { id: 2, username: "CSSNinja", score: 850, challenges: 14, perfectScores: 9, rank: "Master", avatar: "🥇", trend: { direction: "down", change: 1 } },
    { id: 3, username: "PixelPerfect", score: 820, challenges: 13, perfectScores: 8, rank: "Master", avatar: "🥈", trend: { direction: "down", change: 1 } },
    { id: 4, username: "StyleMaster", score: 780, challenges: 12, perfectScores: 7, rank: "Master", avatar: "🥉", trend: { direction: "down", change: 1 } },
    { id: 5, username: "CSSWizard", score: 750, challenges: 11, perfectScores: 6, rank: "Diamond", avatar: "⭐", trend: { direction: "down", change: 1 } },
    { id: 6, username: "GridGuru", score: 680, challenges: 9, perfectScores: 4, rank: "Diamond", avatar: "🎯", trend: { direction: "up", change: 1 } },
    { id: 7, username: "FlexboxHero", score: 650, challenges: 8, perfectScores: 3, rank: "Diamond", avatar: "💎", trend: { direction: "up", change: 2 } },
    { id: 8, username: "WebArtist", score: 620, challenges: 7, perfectScores: 3, rank: "Diamond", avatar: "🎨", trend: { direction: "down", change: 2 } },
    { id: 9, username: "CSSPro", score: 580, challenges: 6, perfectScores: 2, rank: "Platinum", avatar: "🌟", trend: { direction: "same", change: 0 } },
    { id: 10, username: "StyleGenius", score: 550, challenges: 5, perfectScores: 2, rank: "Platinum", avatar: "✨", trend: { direction: "down", change: 1 } },
  ],
  "This Week": [
    { id: 1, username: "YOU", score: 320, challenges: 5, perfectScores: 3, rank: "Diamond", avatar: "👑", trend: { direction: "up", change: 4 } },
    { id: 2, username: "CSSNinja", score: 250, challenges: 4, perfectScores: 2, rank: "Diamond", avatar: "🥇", trend: { direction: "down", change: 1 } },
    { id: 3, username: "PixelPerfect", score: 220, challenges: 3, perfectScores: 2, rank: "Diamond", avatar: "🥈", trend: { direction: "up", change: 1 } },
    { id: 4, username: "StyleMaster", score: 180, challenges: 3, perfectScores: 1, rank: "Diamond", avatar: "🥉", trend: { direction: "down", change: 2 } },
    { id: 5, username: "CSSWizard", score: 150, challenges: 2, perfectScores: 1, rank: "Platinum", avatar: "⭐", trend: { direction: "same", change: 0 } },
    { id: 6, username: "GridGuru", score: 80, challenges: 1, perfectScores: 0, rank: "Platinum", avatar: "🎯", trend: { direction: "up", change: 3 } },
    { id: 7, username: "FlexboxHero", score: 65, challenges: 1, perfectScores: 0, rank: "Gold", avatar: "💎", trend: { direction: "down", change: 1 } },
    { id: 8, username: "WebArtist", score: 62, challenges: 1, perfectScores: 0, rank: "Gold", avatar: "🎨", trend: { direction: "down", change: 3 } },
    { id: 9, username: "CSSPro", score: 58, challenges: 1, perfectScores: 0, rank: "Gold", avatar: "🌟", trend: { direction: "up", change: 1 } },
    { id: 10, username: "StyleGenius", score: 55, challenges: 1, perfectScores: 0, rank: "Gold", avatar: "✨", trend: { direction: "same", change: 0 } },
  ],
  "Today": [
    { id: 1, username: "YOU", score: 85, challenges: 2, perfectScores: 1, rank: "Gold", avatar: "👑", trend: { direction: "up", change: 4 } },
    { id: 2, username: "CSSNinja", score: 50, challenges: 1, perfectScores: 1, rank: "Gold", avatar: "🥇", trend: { direction: "down", change: 1 } },
    { id: 3, username: "PixelPerfect", score: 45, challenges: 1, perfectScores: 1, rank: "Gold", avatar: "🥈", trend: { direction: "same", change: 0 } },
    { id: 4, username: "StyleMaster", score: 40, challenges: 1, perfectScores: 0, rank: "Gold", avatar: "🥉", trend: { direction: "up", change: 2 } },
    { id: 5, username: "CSSWizard", score: 35, challenges: 1, perfectScores: 0, rank: "Platinum", avatar: "⭐", trend: { direction: "down", change: 2 } },
    { id: 6, username: "GridGuru", score: 25, challenges: 1, perfectScores: 0, rank: "Platinum", avatar: "🎯", trend: { direction: "up", change: 1 } },
    { id: 7, username: "FlexboxHero", score: 20, challenges: 0, perfectScores: 0, rank: "Platinum", avatar: "💎", trend: { direction: "down", change: 3 } },
    { id: 8, username: "WebArtist", score: 18, challenges: 0, perfectScores: 0, rank: "Platinum", avatar: "🎨", trend: { direction: "same", change: 0 } },
    { id: 9, username: "CSSPro", score: 15, challenges: 0, perfectScores: 0, rank: "Gold", avatar: "🌟", trend: { direction: "up", change: 1 } },
    { id: 10, username: "StyleGenius", score: 12, challenges: 0, perfectScores: 0, rank: "Gold", avatar: "✨", trend: { direction: "down", change: 1 } },
  ],
};
