import type { MonacoTheme } from "~/types/editor";

export const editorTheme: MonacoTheme = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6272a4", fontStyle: "italic" },
    { token: "keyword", foreground: "ff79c6", fontStyle: "bold" },
    { token: "number", foreground: "bd93f9" },
    { token: "string", foreground: "f1fa8c" },
    { token: "identifier", foreground: "f8f8f2" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "delimiter", foreground: "ff79c6" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
  ],
  colors: {
    "editor.background": "#1a1b26",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#2a2b36",
    "editorLineNumber.foreground": "#565869",
    "editorLineNumber.activeForeground": "#737aa2",
    "editor.selectionBackground": "#44475a",
    "editor.inactiveSelectionBackground": "#3a3d4d",
    "editorCursor.foreground": "#f8f8f2",
    "editor.findMatchBackground": "#ffb86c40",
    "editor.findMatchHighlightBackground": "#ffb86c20",
    "editorBracketMatch.background": "#363948",
    "editorBracketMatch.border": "#565869",
    "editorGutter.background": "#1a1b26",
    "editorWidget.background": "#21222c",
    "editorSuggestWidget.background": "#21222c",
    "editorSuggestWidget.border": "#363948",
    "editorSuggestWidget.selectedBackground": "#44475a",
    "editorSuggestWidget.highlightForeground": "#50fa7b",
    "editorHoverWidget.background": "#21222c",
    "editorHoverWidget.border": "#363948",
  },
};

export const editorOptions = {
  minimap: { enabled: false },
  fontSize: 14,
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  lineNumbers: "on",
  roundedSelection: false,
  scrollBeyondLastLine: false,
  automaticLayout: true,
  padding: { top: 16 },
  wordWrap: "on",
  formatOnPaste: true,
  formatOnType: true,
  tabSize: 2,
  renderLineHighlight: "all",
  suggestOnTriggerCharacters: true,
  acceptSuggestionOnEnter: "on",
  cursorBlinking: "smooth",
  cursorSmoothCaretAnimation: "on",
  smoothScrolling: true,
  folding: true,
  lineDecorationsWidth: 10,
  scrollbar: {
    useShadows: false,
    verticalScrollbarSize: 8,
    horizontalScrollbarSize: 8,
  },
  overviewRulerBorder: false,
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  glyphMargin: false,
  quickSuggestions: {
    other: true,
    comments: true,
    strings: true,
  },
  contextmenu: true,
  mouseWheelZoom: true,
  suggest: {
    showKeywords: true,
    showSnippets: true,
    showClasses: true,
    showColors: true,
    showFiles: true,
    showFunctions: true,
    showModules: true,
    showProperties: true,
    showWords: true,
    showValues: true,
  },
} as const;
